name: GabAI CD/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #-------------------------------------
  # Job 1: Run Jest Tests
  #-------------------------------------
  test:
    name: run tests on Jest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run jest test
        run: npm test

  #-------------------------------------
  # Job 2: Build Next.js App
  #-------------------------------------

  build:
    name: build next.js app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

  #-------------------------------------
  # Job 3: Deploy to Vercel
  #-------------------------------------

  deploy:
    name: deploy to Vercel
    runs-on: ubuntu-latest

    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod" # Triggers a production deployment

